name: ci

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: docker-push
    env:
      VERSION: 0.0.1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      -
        name: unzip
        run: unzip -P ${{ secrets.APP_PASSWORD }} app.zip
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/df-server:${{ env.VERSION }} , ${{ secrets.DOCKERHUB_USERNAME }}/df-server:latest